# Generated by Django 4.2.15 on 2024-08-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("articleid", models.IntegerField(unique=True)),
                ("subarticleid", models.IntegerField(unique=True)),
                ("articlename", models.CharField(max_length=256)),
                ("external_str_id", models.CharField(max_length=256, unique=True)),
                ("ecrlongname", models.CharField(max_length=256)),
            ],
        ),
    ]
