# Generated by Django 4.2.15 on 2024-08-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="external_str_id",
            field=models.CharField(max_length=256),
        ),
    ]
